LIBITD-2593. Updated "mocha" gem to v2.x
Updated the "mocha" gem to 2.8.2 to fix the following error that
was occurring when running the tests:

```
rake test
...
NameError: uninitialized constant MiniTest
Did you mean?  Minitest
...
```

This was apparently caused by a naming issue in the “mocha” gem and
minitest v5.19, see https://github.com/freerange/mocha/issues/614

Updating to the latest 2.x release corrects the issue.

https://umd-dit.atlassian.net/browse/LIBITD-2593