LIBITD-2593. Added "logger" as a dependency to "config/boot.rb"
Added "logger" as a dependency to "config/boot.rb", because with the
upgrade of the "concurrent-ruby" gem to 1.3.5 as part of the
Rails v6.1.7.10 updated, the following error was occurring:

```
NameError: uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger
/Users/dsteelma/.rvm/gems/ruby-2.7.5@student-applications/gems/activesupport-6.1.7.10/lib/active_support/logger_thread_safe_level.rb:16:in `<module:LoggerThreadSafeLevel>'
/Users/dsteelma/.rvm/gems/ruby-2.7.5@student-applications/gems/activesupport-6.1.7.10/lib/active_support/logger_thread_safe_level.rb:9:in `<module:ActiveSupport>'
...
```

See https://stackoverflow.com/questions/79360526/uninitialized-constant-activesupportloggerthreadsafelevellogger-nameerror
which indicates that this error is caused because the "concurrent-ruby"
gem removed its dependency on the logger, exposing this issue.

https://umd-dit.atlassian.net/browse/LIBITD-2593